---
- hosts: vm
  environment:
    http_proxy: "{{proxy.http_proxy}}"
    https_proxy: "{{proxy.https_proxy}}"
    no_proxy: "{{proxy.no_proxy}}"
  roles:
    - {role: topo/destroy, tags: topo_destroy}
    - {role: cluster/destroy, tags: cluster_destroy}
