## © 2023 Nephio Authors
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0
---

- name: login into dockerhub using podman runtime
  containers.podman.podman_login:
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_token }}"
    registry: docker.io