## © 2022 Nephio Authors
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0

---
- name: installing clab
  become: true
  shell: bash -c "$(wget -qO - https://get.containerlab.dev)"
